/// ChunkManager - Manages chunk loading, unloading, and meshing
/// Coordinates between main thread and worker threads
const std = @import("std");
const Io = std.Io;
const shared = @import("Shared");
const renderer = @import("Renderer");
const volk = @import("volk");
const vk = volk.c;

const Logger = shared.Logger;
const profiler = shared.profiler;
const Vec3 = shared.Vec3;
const Chunk = shared.Chunk;
const ChunkPos = shared.ChunkPos;
const ChunkPosContext = shared.ChunkPosContext;
const CHUNK_SIZE = shared.CHUNK_SIZE;
const TerrainGenerator = shared.TerrainGenerator;
const Rcu = shared.Rcu;
const BlockEntry = shared.BlockEntry;

const RenderSystem = renderer.RenderSystem;
const TextureManager = renderer.TextureManager;
const Vertex = renderer.Vertex;
const BlockModelShaper = renderer.block.BlockModelShaper;
const ModelLoader = renderer.block.ModelLoader;
const BlockstateLoader = renderer.block.BlockstateLoader;
const ChunkBufferManager = renderer.buffer.ChunkBufferManager;
const ChunkBufferConfig = renderer.buffer.ChunkBufferConfig;
const ChunkBufferAllocation = renderer.buffer.ChunkBufferAllocation;
const ChunkDrawCommand = RenderSystem.ChunkDrawCommand;
const StagingCopy = RenderSystem.StagingCopy;

const render_chunk = @import("RenderChunk.zig");
const RenderChunk = render_chunk.RenderChunk;
const ChunkMesh = render_chunk.ChunkMesh;
const ChunkState = render_chunk.ChunkState;
const CompletedMesh = render_chunk.CompletedMesh;
const RENDER_LAYER_COUNT = render_chunk.RENDER_LAYER_COUNT;

const thread_pool = @import("ThreadPool.zig");
const ThreadPool = thread_pool.ThreadPool;
const ThreadSafeQueue = thread_pool.ThreadSafeQueue;
const Task = thread_pool.Task;
const WorkerContext = thread_pool.WorkerContext;

const chunk_mesher = @import("ChunkMesher.zig");
const ChunkMesher = chunk_mesher.ChunkMesher;
const WorkerMeshContext = chunk_mesher.WorkerMeshContext;

const chunk_storage = @import("ChunkStorage.zig");
const ChunkStorage = chunk_storage.ChunkStorage;

/// Task type for chunk operations
pub const ChunkTaskType = enum {
    /// Generate terrain + mesh (new chunk)
    generate,
    /// Mesh only (existing chunk modified)
    remesh,
};

/// Task data for chunk generation/meshing
pub const ChunkTask = struct {
    pos: ChunkPos,
    task_type: ChunkTaskType,
    /// For remesh tasks: the existing chunk data
    /// For generate tasks: uninitialized (will be generated by worker)
    chunk: Chunk,
    neighbors: [6]?*const Chunk,
    /// Pointer to the RenderChunk for storing generated data
    render_chunk: *RenderChunk,
};

/// Configuration for chunk loading
pub const ChunkConfig = struct {
    /// Horizontal view distance in chunks
    view_distance: u32 = 4,
    /// Vertical view distance in chunk sections
    vertical_view_distance: u32 = 4,
    /// Distance at which to unload chunks (hysteresis)
    unload_distance: u32 = 6,
    /// Number of worker threads
    worker_count: u8 = 4,
    /// Maximum chunk uploads per frame
    max_uploads_per_tick: u8 = 4,
    /// Maximum chunks to queue per update (C2ME-style rate limiting)
    /// Prevents frame spikes when entering new areas by spreading chunk loading across frames
    max_chunks_per_update: u16 = 32,
};

/// Per-worker data containing both manager reference and thread-local mesh context
/// This eliminates per-chunk allocations by reusing pre-allocated buffers
pub const WorkerData = struct {
    /// Reference to the ChunkManager (for shared resources)
    manager: *ChunkManager,
    /// Thread-local mesh context with pre-allocated buffers
    mesh_context: *WorkerMeshContext,
};

pub const ChunkManager = struct {
    const Self = @This();
    const logger = Logger.scoped(Self);

    /// HashSet for pending positions
    const PosSet = std.HashMap(ChunkPos, void, ChunkPosContext, std.hash_map.default_max_load_percentage);

    allocator: std.mem.Allocator,
    io: Io,

    /// Currently loaded chunks (ring buffer storage)
    chunk_storage: ChunkStorage,

    /// Positions queued for loading (prevents duplicate tasks)
    pending_loads: PosSet,

    /// Completed meshes ready for GPU upload
    completed_queue: ThreadSafeQueue(CompletedMesh),

    /// Thread pool for async operations
    pool: ThreadPool,

    /// Current player chunk position
    player_chunk: ChunkPos,

    /// Configuration
    config: ChunkConfig,

    /// Reference to render system for GPU uploads
    render_system: *RenderSystem,

    /// Shared texture manager reference (read-only, thread-safe)
    texture_manager: *TextureManager,

    /// Asset directory for model loading
    asset_directory: []const u8,

    /// Shared block model shaper (pre-warmed, read-only after init)
    shared_model_shaper: ?*BlockModelShaper = null,
    shared_model_loader: ?*ModelLoader = null,
    shared_blockstate_loader: ?*BlockstateLoader = null,

    /// Buffer manager for GPU buffer arena allocation
    buffer_manager: ?*ChunkBufferManager = null,

    /// Terrain generator for procedural chunk generation
    terrain_generator: ?*TerrainGenerator = null,

    /// Reusable draw commands list
    draw_commands: std.ArrayListUnmanaged(ChunkDrawCommand) = .{},

    /// Reusable staging copies list
    staging_copies: std.ArrayListUnmanaged(StagingCopy) = .{},

    /// C2ME-style consolidation: defer updateLoadQueue to once per frame
    /// This prevents cascading slowdowns when multiple ticks run in one frame
    load_queue_dirty: bool = false,

    /// Cached vertex buffer list for multi-arena rendering
    vertex_buffer_cache: std.ArrayListUnmanaged(vk.VkBuffer) = .{},

    /// Cached index buffer list for multi-arena rendering
    index_buffer_cache: std.ArrayListUnmanaged(vk.VkBuffer) = .{},

    /// RCU for safe concurrent chunk access
    /// Protects neighbor chunk pointers during meshing
    rcu: ?*Rcu = null,

    /// Per-worker data with thread-local mesh contexts (C2ME-style optimization)
    /// Eliminates ~2.4MB of allocations per chunk by reusing buffers
    worker_data: ?[]WorkerData = null,

    /// Initialize the chunk manager
    pub fn init(
        allocator: std.mem.Allocator,
        io: Io,
        render_system: *RenderSystem,
        texture_manager: *TextureManager,
        asset_directory: []const u8,
        config: ChunkConfig,
    ) !Self {
        logger.info("Initializing ChunkManager with view distance {}", .{config.view_distance});

        const storage = try ChunkStorage.init(allocator, config.unload_distance, config.vertical_view_distance);

        const self = Self{
            .allocator = allocator,
            .io = io,
            .chunk_storage = storage,
            .pending_loads = PosSet.init(allocator),
            .completed_queue = ThreadSafeQueue(CompletedMesh).init(allocator),
            .pool = try ThreadPool.init(allocator, config.worker_count, processTask),
            .player_chunk = ChunkPos{ .x = 0, .z = 0, .section_y = 0 },
            .config = config,
            .render_system = render_system,
            .texture_manager = texture_manager,
            .asset_directory = asset_directory,
        };

        return self;
    }

    /// Start the worker threads
    pub fn start(self: *Self) !void {
        // Initialize buffer manager for GPU buffer arena allocation
        const buffer_mgr = try self.allocator.create(ChunkBufferManager);
        buffer_mgr.* = try ChunkBufferManager.init(
            self.allocator,
            self.render_system.getDevice(),
            self.render_system.getPhysicalDevice(),
            ChunkBufferConfig{
                .view_distance = self.config.view_distance,
                .vertical_view_distance = self.config.vertical_view_distance,
            },
        );
        self.buffer_manager = buffer_mgr;

        // Initialize shared model loading resources (pre-warmed, read-only for workers)
        const model_loader = try self.allocator.create(ModelLoader);
        model_loader.* = ModelLoader.init(self.allocator, self.io, self.asset_directory);
        self.shared_model_loader = model_loader;

        const blockstate_loader = try self.allocator.create(BlockstateLoader);
        blockstate_loader.* = BlockstateLoader.init(self.allocator, self.io, self.asset_directory);
        self.shared_blockstate_loader = blockstate_loader;

        const shaper = try self.allocator.create(BlockModelShaper);
        shaper.* = BlockModelShaper.init(
            self.allocator,
            model_loader,
            blockstate_loader,
            self.texture_manager,
        );
        self.shared_model_shaper = shaper;

        // Pre-warm model cache with all blocks
        for (1..256) |id| {
            _ = shaper.getModel(BlockEntry.simple(@intCast(id))) catch {};
        }
        logger.info("Model cache pre-warmed", .{});

        // Initialize RCU for safe concurrent chunk access
        const rcu_instance = try self.allocator.create(Rcu);
        rcu_instance.* = Rcu.init(self.allocator, self.config.worker_count);
        self.rcu = rcu_instance;
        logger.info("RCU initialized for {} worker threads", .{self.config.worker_count});

        // Initialize terrain generator
        const terrain_gen = try self.allocator.create(TerrainGenerator);
        terrain_gen.* = TerrainGenerator.init(.{ .seed = 12345 }) orelse {
            logger.err("Failed to initialize terrain generator", .{});
            self.allocator.destroy(terrain_gen);
            return error.TerrainGeneratorInitFailed;
        };
        self.terrain_generator = terrain_gen;
        logger.info("Terrain generator initialized with ridged terrain", .{});

        // Start pool first (this initializes contexts)
        try self.pool.start();

        // Initialize per-worker thread-local mesh contexts (C2ME-style optimization)
        // Each worker gets ~3.6MB of pre-allocated buffers that are reused across all chunks
        const worker_count = self.config.worker_count;
        self.worker_data = try self.allocator.alloc(WorkerData, worker_count);

        for (0..worker_count) |i| {
            // Create the mesh context with pre-allocated buffers
            const mesh_ctx = try self.allocator.create(WorkerMeshContext);
            mesh_ctx.* = try WorkerMeshContext.init(self.allocator);

            self.worker_data.?[i] = WorkerData{
                .manager = self,
                .mesh_context = mesh_ctx,
            };

            // Set user data to point to our WorkerData struct
            self.pool.setWorkerData(i, @ptrCast(&self.worker_data.?[i]));
        }

        const total_buffer_mb = @as(f32, @floatFromInt(worker_count)) * 3.6;
        logger.info("ChunkManager started with {} workers (~{d:.1}MB thread-local buffers)", .{ worker_count, total_buffer_mb });
    }

    /// Shutdown and cleanup
    pub fn deinit(self: *Self) void {
        logger.info("Shutting down ChunkManager...", .{});

        // Shutdown thread pool
        self.pool.shutdown();
        self.pool.deinit();

        // Free per-worker thread-local mesh contexts
        if (self.worker_data) |workers| {
            for (workers) |*wd| {
                wd.mesh_context.deinit();
                self.allocator.destroy(wd.mesh_context);
            }
            self.allocator.free(workers);
            self.worker_data = null;
        }

        // Synchronize RCU and free deferred items
        // This must happen after pool shutdown to ensure all workers have exited
        if (self.rcu) |rcu_instance| {
            logger.info("Synchronizing RCU before cleanup...", .{});
            rcu_instance.synchronize();
            rcu_instance.deinit();
            self.allocator.destroy(rcu_instance);
            self.rcu = null;
        }

        // Free shared model resources
        if (self.shared_model_shaper) |shaper| {
            shaper.deinit();
            self.allocator.destroy(shaper);
        }
        if (self.shared_blockstate_loader) |loader| {
            loader.deinit();
            self.allocator.destroy(loader);
        }
        if (self.shared_model_loader) |loader| {
            loader.deinit();
            self.allocator.destroy(loader);
        }

        // Free loaded chunks (and their buffer allocations)
        var iter = self.chunk_storage.iterator();
        while (iter.next()) |entry| {
            const chunk = entry.value_ptr.*;
            // Free buffer allocation if present
            if (self.buffer_manager) |buf_mgr| {
                if (chunk.getBufferAllocation()) |alloc| {
                    buf_mgr.free(alloc);
                }
            }
            chunk.deinit();
            self.allocator.destroy(chunk);
        }
        self.chunk_storage.deinit();

        // Free pending queues
        self.pending_loads.deinit();

        // Free completed meshes that weren't processed
        while (self.completed_queue.tryPop()) |*mesh| {
            var m = mesh.*;
            m.deinit();
        }
        self.completed_queue.deinit();

        // Free draw commands, staging copies, and buffer caches
        self.draw_commands.deinit(self.allocator);
        self.staging_copies.deinit(self.allocator);
        self.vertex_buffer_cache.deinit(self.allocator);
        self.index_buffer_cache.deinit(self.allocator);

        // Free buffer manager
        if (self.buffer_manager) |buf_mgr| {
            buf_mgr.deinit();
            self.allocator.destroy(buf_mgr);
        }

        // Free terrain generator
        if (self.terrain_generator) |terrain_gen| {
            terrain_gen.deinit();
            self.allocator.destroy(terrain_gen);
        }

        logger.info("ChunkManager shutdown complete", .{});
    }

    /// Update player position and queue chunks for loading/unloading
    pub fn updatePlayerPosition(self: *Self, position: Vec3) void {
        const zone = profiler.trace(@src());
        defer zone.end();

        const new_chunk = ChunkPos.fromWorldPos(position.x, position.y, position.z);

        // Only update if player moved to a new chunk
        if (new_chunk.eql(self.player_chunk)) return;

        self.player_chunk = new_chunk;

        // Update thread pool's camera position for dynamic priority calculation
        // This ensures closest chunks are always processed first, even as player moves
        self.pool.updateCameraPos(new_chunk.x, new_chunk.z, new_chunk.section_y);

        // C2ME-style consolidation: Mark dirty instead of immediate update
        // The actual updateLoadQueue will be called once per frame in flushLoadQueue()
        // This prevents cascading slowdowns when multiple ticks run in one frame
        self.load_queue_dirty = true;
    }

    /// C2ME-style: Flush consolidated load queue updates once per frame
    /// Call this ONCE per frame, after all ticks have run, not per tick
    pub fn flushLoadQueue(self: *Self) void {
        if (!self.load_queue_dirty) return;
        self.load_queue_dirty = false;
        self.updateLoadQueue();
    }

    /// Begin a new frame - call this before tick() with the current frame fence
    /// This ensures staging buffer synchronization
    pub fn beginFrame(self: *Self, frame_fence: vk.VkFence) void {
        if (self.buffer_manager) |buf_mgr| {
            buf_mgr.beginFrame(frame_fence) catch |err| {
                logger.warn("Failed to begin frame for buffer manager: {}", .{err});
            };
        }
    }

    /// Process completed meshes and update chunks
    /// Call this once per frame from the main thread (after beginFrame)
    pub fn tick(self: *Self) void {
        const zone = profiler.trace(@src());
        defer zone.end();

        // Tracy plots for monitoring chunk system health
        profiler.plotInt("LoadedChunks", @intCast(self.chunk_storage.count));
        profiler.plotInt("PendingLoads", @intCast(self.pending_loads.count()));
        profiler.plotInt("TaskQueueLen", @intCast(self.pool.pendingTasks()));
        profiler.plotInt("CompletedQueue", @intCast(self.completed_queue.len()));

        const buf_mgr = self.buffer_manager orelse return;

        // Process completed meshes (limit per frame to avoid stalls)
        var uploads: u8 = 0;
        while (uploads < self.config.max_uploads_per_tick) {
            const mesh_opt = self.completed_queue.tryPop();
            if (mesh_opt == null) break;

            var mesh = mesh_opt.?;

            // STALENESS CHECK: Skip chunks that moved out of view range while queued
            // This is the key optimization - when flying fast, many queued meshes are
            // already behind the player. Don't waste GPU upload time on them.
            const dx = if (mesh.pos.x > self.player_chunk.x)
                mesh.pos.x - self.player_chunk.x
            else
                self.player_chunk.x - mesh.pos.x;
            const dz = if (mesh.pos.z > self.player_chunk.z)
                mesh.pos.z - self.player_chunk.z
            else
                self.player_chunk.z - mesh.pos.z;
            const dy = if (mesh.pos.section_y > self.player_chunk.section_y)
                mesh.pos.section_y - self.player_chunk.section_y
            else
                self.player_chunk.section_y - mesh.pos.section_y;

            const horizontal_dist = @max(dx, dz);
            const is_stale = horizontal_dist > self.config.unload_distance or
                dy > self.config.vertical_view_distance + 2;

            if (is_stale) {
                // Chunk is out of range - the unload logic will handle cleanup
                // Just free the mesh data and skip the expensive GPU upload
                mesh.deinit();
                _ = self.pending_loads.remove(mesh.pos);
                continue;
            }

            // Find the corresponding render chunk
            if (self.chunk_storage.get(mesh.pos)) |render_chunk_ptr| {
                // Copy generated chunk data if present (for generation tasks)
                // This must happen before any collision/block access uses this chunk
                if (mesh.generated_chunk) |gen_chunk| {
                    render_chunk_ptr.chunk = gen_chunk;
                }

                // Handle empty meshes (e.g., all-air chunks)
                const total_vertices = mesh.getTotalVertexCount();
                const total_indices = mesh.getTotalIndexCount();
                if (total_vertices == 0 or total_indices == 0) {
                    // Still mark as ready - chunk data is valid, just no visible geometry
                    render_chunk_ptr.setState(.ready);
                    mesh.deinit();
                    _ = self.pending_loads.remove(mesh.pos);
                    continue;
                }

                // Validate indices are within vertex bounds for each layer
                var valid = true;
                for (0..RENDER_LAYER_COUNT) |i| {
                    const layer = &mesh.layers[i];
                    if (layer.vertices.len == 0) continue;

                    var max_index: u32 = 0;
                    for (layer.indices) |idx| {
                        if (idx > max_index) max_index = idx;
                    }
                    if (max_index >= layer.vertices.len) {
                        logger.err("Chunk ({},{},{}) layer {} has invalid index {} >= vertex count {}", .{
                            mesh.pos.x,
                            mesh.pos.z,
                            mesh.pos.section_y,
                            i,
                            max_index,
                            layer.vertices.len,
                        });
                        valid = false;
                        break;
                    }
                }
                if (!valid) {
                    mesh.deinit();
                    _ = self.pending_loads.remove(mesh.pos);
                    continue;
                }

                // Allocate buffer space for each non-empty layer
                var layer_allocations: [RENDER_LAYER_COUNT]?ChunkBufferAllocation = .{ null, null, null };
                var allocation_failed = false;

                for (0..RENDER_LAYER_COUNT) |i| {
                    const layer = &mesh.layers[i];
                    if (layer.vertices.len == 0) continue;

                    layer_allocations[i] = buf_mgr.allocate(
                        @intCast(layer.vertices.len),
                        @intCast(layer.indices.len),
                    );
                    if (layer_allocations[i] == null) {
                        logger.warn("Failed to allocate buffer space for chunk layer {}", .{i});
                        allocation_failed = true;
                        break;
                    }
                }

                if (allocation_failed) {
                    // Free any allocations we did make
                    for (layer_allocations) |alloc_opt| {
                        if (alloc_opt) |alloc| {
                            buf_mgr.free(alloc);
                        }
                    }
                    // Remove from pending so chunk can be re-queued on next update
                    _ = self.pending_loads.remove(mesh.pos);
                    mesh.deinit();
                    continue;
                }

                // Stage vertex and index data for each layer
                var staging_failed = false;
                for (0..RENDER_LAYER_COUNT) |i| {
                    const layer = &mesh.layers[i];
                    const alloc_opt = layer_allocations[i];
                    if (alloc_opt == null) continue;
                    const allocation = alloc_opt.?;

                    // Stage vertex data
                    const vertex_bytes = std.mem.sliceAsBytes(layer.vertices);
                    buf_mgr.stageVertices(allocation, vertex_bytes) catch |err| {
                        logger.warn("Failed to stage vertex data for layer {}: {}", .{ i, err });
                        staging_failed = true;
                        break;
                    };

                    // Stage index data
                    const index_bytes = std.mem.sliceAsBytes(layer.indices);
                    buf_mgr.stageIndices(allocation, index_bytes) catch |err| {
                        logger.warn("Failed to stage index data for layer {}: {}", .{ i, err });
                        staging_failed = true;
                        break;
                    };
                }

                if (staging_failed) {
                    for (layer_allocations) |alloc_opt| {
                        if (alloc_opt) |alloc| {
                            buf_mgr.free(alloc);
                        }
                    }
                    // Remove from pending so chunk can be re-queued on next update
                    _ = self.pending_loads.remove(mesh.pos);
                    mesh.deinit();
                    continue;
                }

                // Prepare per-layer vertex/index slices for ChunkMesh.init
                var layer_vertices: [RENDER_LAYER_COUNT][]const Vertex = undefined;
                var layer_indices: [RENDER_LAYER_COUNT][]const u32 = undefined;
                for (0..RENDER_LAYER_COUNT) |i| {
                    layer_vertices[i] = mesh.layers[i].vertices;
                    layer_indices[i] = mesh.layers[i].indices;
                }

                // Create ChunkMesh with per-layer allocations
                var chunk_mesh = ChunkMesh.init(
                    self.allocator,
                    layer_vertices,
                    layer_indices,
                ) catch {
                    logger.warn("Failed to create chunk mesh", .{});
                    for (layer_allocations) |alloc_opt| {
                        if (alloc_opt) |alloc| {
                            buf_mgr.free(alloc);
                        }
                    }
                    // Remove from pending so chunk can be re-queued on next update
                    _ = self.pending_loads.remove(mesh.pos);
                    mesh.deinit();
                    continue;
                };

                // Set buffer allocations for each layer
                for (0..RENDER_LAYER_COUNT) |i| {
                    if (layer_allocations[i]) |alloc| {
                        chunk_mesh.setLayerBufferAllocation(i, alloc);
                    }
                }

                // Free OLD buffer allocations BEFORE swapping (atomic swap pattern)
                const old_allocations = render_chunk_ptr.getBufferAllocations();
                for (old_allocations) |old_alloc_opt| {
                    if (old_alloc_opt) |old_alloc| {
                        buf_mgr.free(old_alloc);
                    }
                }

                // Store mesh in render chunk (this frees old mesh CPU data)
                render_chunk_ptr.setMesh(chunk_mesh);

                // Remove from pending
                _ = self.pending_loads.remove(mesh.pos);

                uploads += 1;
            }

            // Free the completed mesh data (ChunkMesh made a copy)
            mesh.deinit();
        }

        // Advance RCU epoch to free deferred chunk deletions
        // This allows chunks that were unloaded in previous frames to be freed
        // once all workers have exited their critical sections
        if (self.rcu) |rcu_instance| {
            _ = rcu_instance.tryAdvance();
        }
    }

    /// Commit staged uploads to GPU (call before rendering)
    /// Returns true if there were uploads to commit
    pub fn commitUploads(self: *Self, cmd_buffer: vk.VkCommandBuffer) bool {
        const buf_mgr = self.buffer_manager orelse return false;
        if (!buf_mgr.hasPendingUploads()) return false;
        buf_mgr.commitUploads(cmd_buffer);
        return true;
    }

    /// Get draw commands for all ready chunks
    /// Commands are sorted by render layer: solid (0), cutout (1), translucent (2)
    pub fn getDrawCommands(self: *Self) []const ChunkDrawCommand {
        const zone = profiler.trace(@src());
        defer zone.end();

        self.draw_commands.clearRetainingCapacity();

        // Sanity checks - offsets should be aligned
        const vertex_size: u64 = 36; // sizeof(Vertex)
        const index_size: u64 = 4; // sizeof(u32)

        // Single pass: collect all draw commands from all chunks and all layers
        var iter = self.chunk_storage.iterator();
        while (iter.next()) |entry| {
            const chunk = entry.value_ptr.*;

            // Render chunks that are ready OR dirty (dirty = rebuilding, still has old mesh)
            const state = chunk.getState();
            if (state != .ready and state != .dirty) continue;

            const m = chunk.mesh orelse continue;

            // Generate commands for all non-empty layers in this chunk
            for (0..RENDER_LAYER_COUNT) |layer_idx| {
                const layer = &m.layers[layer_idx];
                if (layer.index_count == 0) continue;
                if (!layer.buffer_allocation.valid or !layer.uploaded) continue;

                const vertex_offset = layer.buffer_allocation.vertex_slice.offset;
                const index_offset = layer.buffer_allocation.index_slice.offset;

                if (vertex_offset % vertex_size != 0) {
                    logger.warn("Chunk ({},{},{}) layer {} has unaligned vertex offset: {}", .{
                        chunk.pos.x,
                        chunk.pos.z,
                        chunk.pos.section_y,
                        layer_idx,
                        vertex_offset,
                    });
                    continue;
                }
                if (index_offset % index_size != 0) {
                    logger.warn("Chunk ({},{},{}) layer {} has unaligned index offset: {}", .{
                        chunk.pos.x,
                        chunk.pos.z,
                        chunk.pos.section_y,
                        layer_idx,
                        index_offset,
                    });
                    continue;
                }

                self.draw_commands.append(self.allocator, ChunkDrawCommand{
                    .vertex_offset = vertex_offset,
                    .index_offset = index_offset,
                    .index_count = layer.index_count,
                    .vertex_arena = layer.buffer_allocation.vertex_slice.arena_index,
                    .index_arena = layer.buffer_allocation.index_slice.arena_index,
                    .render_layer = @intCast(layer_idx),
                }) catch continue;
            }
        }

        // Sort draw commands by (render_layer, vertex_arena, index_arena) for:
        // 1. Proper rendering order: solid (0) -> cutout (1) -> translucent (2)
        // 2. Batching commands with same pipeline and buffer bindings for indirect drawing
        std.mem.sort(ChunkDrawCommand, self.draw_commands.items, {}, struct {
            fn lessThan(_: void, a: ChunkDrawCommand, b: ChunkDrawCommand) bool {
                if (a.render_layer != b.render_layer) return a.render_layer < b.render_layer;
                if (a.vertex_arena != b.vertex_arena) return a.vertex_arena < b.vertex_arena;
                return a.index_arena < b.index_arena;
            }
        }.lessThan);

        return self.draw_commands.items;
    }

    /// Get the primary vertex buffer for rendering (arena 0)
    /// For multi-buffer rendering, use getVertexBufferForArena()
    pub fn getVertexBuffer(self: *const Self) ?vk.VkBuffer {
        const buf_mgr = self.buffer_manager orelse return null;
        return buf_mgr.getPrimaryVertexBuffer();
    }

    /// Get the primary index buffer for rendering (arena 0)
    /// For multi-buffer rendering, use getIndexBufferForArena()
    pub fn getIndexBuffer(self: *const Self) ?vk.VkBuffer {
        const buf_mgr = self.buffer_manager orelse return null;
        return buf_mgr.getPrimaryIndexBuffer();
    }

    /// Get a vertex buffer for a specific arena index
    pub fn getVertexBufferForArena(self: *const Self, arena_index: u16) ?vk.VkBuffer {
        const buf_mgr = self.buffer_manager orelse return null;
        return buf_mgr.getVertexBuffer(arena_index);
    }

    /// Get an index buffer for a specific arena index
    pub fn getIndexBufferForArena(self: *const Self, arena_index: u16) ?vk.VkBuffer {
        const buf_mgr = self.buffer_manager orelse return null;
        return buf_mgr.getIndexBuffer(arena_index);
    }

    /// Get the number of vertex buffer arenas
    pub fn getVertexArenaCount(self: *const Self) usize {
        const buf_mgr = self.buffer_manager orelse return 0;
        return buf_mgr.getVertexArenaCount();
    }

    /// Get all vertex buffers for multi-arena rendering
    /// Returns a slice of VkBuffers, one per arena
    pub fn getAllVertexBuffers(self: *Self) []const vk.VkBuffer {
        const buf_mgr = self.buffer_manager orelse return &.{};
        const count = buf_mgr.getVertexArenaCount();

        self.vertex_buffer_cache.clearRetainingCapacity();
        for (0..count) |i| {
            if (buf_mgr.getVertexBuffer(@intCast(i))) |buf| {
                self.vertex_buffer_cache.append(self.allocator, buf) catch continue;
            }
        }
        return self.vertex_buffer_cache.items;
    }

    /// Get all index buffers for multi-arena rendering
    /// Returns a slice of VkBuffers, one per arena
    pub fn getAllIndexBuffers(self: *Self) []const vk.VkBuffer {
        const buf_mgr = self.buffer_manager orelse return &.{};
        const count = buf_mgr.getIndexArenaCount();

        self.index_buffer_cache.clearRetainingCapacity();
        for (0..count) |i| {
            if (buf_mgr.getIndexBuffer(@intCast(i))) |buf| {
                self.index_buffer_cache.append(self.allocator, buf) catch continue;
            }
        }
        return self.index_buffer_cache.items;
    }

    /// Get pending staging copies for GPU upload
    /// Call this after tick() and before drawFrameMultiChunk()
    pub fn getStagingCopies(self: *Self) []const StagingCopy {
        const buf_mgr = self.buffer_manager orelse return &.{};

        // Build staging copies from pending copies
        self.staging_copies.clearRetainingCapacity();

        const staging_buffer = buf_mgr.getStagingBuffer();
        const pending = buf_mgr.getPendingCopies();

        for (pending) |copy| {
            self.staging_copies.append(self.allocator, StagingCopy{
                .src_buffer = staging_buffer,
                .src_offset = copy.src_offset,
                .dst_buffer = copy.dst_buffer,
                .dst_offset = copy.dst_offset,
                .size = copy.size,
            }) catch continue;
        }

        return self.staging_copies.items;
    }

    /// Clear pending staging copies after they've been committed
    pub fn clearStagingCopies(self: *Self) void {
        if (self.buffer_manager) |buf_mgr| {
            buf_mgr.clearPendingCopies();
        }
        self.staging_copies.clearRetainingCapacity();
    }

    /// Get all chunks ready for rendering
    pub fn getVisibleChunks(self: *Self) []*RenderChunk {
        var result = std.ArrayList(*RenderChunk).init(self.allocator);

        var iter = self.chunk_storage.iterator();
        while (iter.next()) |entry| {
            const chunk = entry.value_ptr.*;
            if (chunk.isReady()) {
                result.append(chunk) catch continue;
            }
        }

        return result.toOwnedSlice() catch &.{};
    }

    /// Queue chunks for loading based on player position
    /// C2ME-style rate limiting: Only queue up to max_chunks_per_update per call
    /// This prevents frame spikes when entering new areas
    fn updateLoadQueue(self: *Self) void {
        const zone = profiler.trace(@src());
        defer zone.end();

        const view_dist: i32 = @intCast(self.config.view_distance);
        const vert_dist: i32 = @intCast(self.config.vertical_view_distance);
        const max_per_update: u32 = @intCast(self.config.max_chunks_per_update);

        // Queue chunks within view distance (rate limited)
        var chunks_queued: u32 = 0;
        var chunks_skipped_loaded: u32 = 0;
        var chunks_skipped_pending: u32 = 0;
        var hit_limit = false;
        {
            const scan_zone = profiler.traceNamed("ScanForNewChunks");
            defer scan_zone.end();

            var dx: i32 = -view_dist;
            outer: while (dx <= view_dist) : (dx += 1) {
                var dz: i32 = -view_dist;
                while (dz <= view_dist) : (dz += 1) {
                    var dy: i32 = -vert_dist;
                    while (dy <= vert_dist) : (dy += 1) {
                        const pos = ChunkPos{
                            .x = self.player_chunk.x + dx,
                            .z = self.player_chunk.z + dz,
                            .section_y = self.player_chunk.section_y + dy,
                        };

                        // Skip if already loaded or pending
                        if (self.chunk_storage.contains(pos)) {
                            chunks_skipped_loaded += 1;
                            continue;
                        }
                        if (self.pending_loads.contains(pos)) {
                            chunks_skipped_pending += 1;
                            continue;
                        }

                        // Check distance
                        if (!pos.isWithinDistance(self.player_chunk, self.config.view_distance)) continue;

                        // Queue for loading
                        self.queueChunkLoad(pos);
                        chunks_queued += 1;

                        // C2ME-style rate limiting: Stop early if we've queued enough chunks
                        // Remaining chunks will be queued in subsequent frames
                        if (chunks_queued >= max_per_update) {
                            hit_limit = true;
                            break :outer;
                        }
                    }
                }
            }
        }

        // If we hit the limit, mark dirty so we continue next frame
        if (hit_limit) {
            self.load_queue_dirty = true;
        }

        // Tracy plots for scan metrics
        profiler.plotInt("ChunksQueued", @intCast(chunks_queued));
        profiler.plotInt("ChunksSkippedLoaded", @intCast(chunks_skipped_loaded));
        profiler.plotInt("ChunksSkippedPending", @intCast(chunks_skipped_pending));
        zone.setValue(chunks_queued);

        // Unload distant chunks
        self.unloadDistantChunks();
    }

    /// Queue a chunk position for loading
    fn queueChunkLoad(self: *Self, pos: ChunkPos) void {
        const zone = profiler.trace(@src());
        defer zone.end();

        // Mark as pending
        self.pending_loads.put(pos, {}) catch return;

        // Create render chunk placeholder
        const render_chunk_ptr = self.allocator.create(RenderChunk) catch return;
        render_chunk_ptr.* = RenderChunk.init(self.allocator, pos);

        // Put in storage - if there was an existing chunk at this slot (shouldn't happen),
        // we need to clean it up
        const previous = self.chunk_storage.put(pos, render_chunk_ptr) catch {
            self.allocator.destroy(render_chunk_ptr);
            _ = self.pending_loads.remove(pos);
            return;
        };
        if (previous) |old_chunk| {
            // This shouldn't happen if unloading works correctly, but handle it safely
            if (self.buffer_manager) |buf_mgr| {
                if (old_chunk.getBufferAllocation()) |alloc| {
                    buf_mgr.free(alloc);
                }
            }
            old_chunk.deinit();
            self.allocator.destroy(old_chunk);
        }

        // State stays as .loading - worker will generate terrain + mesh

        // Create task data - terrain will be generated by worker thread
        const task_data = self.allocator.create(ChunkTask) catch {
            // LEAK FIX: Clean up RenderChunk if task allocation fails
            _ = self.chunk_storage.remove(pos);
            render_chunk_ptr.deinit();
            self.allocator.destroy(render_chunk_ptr);
            _ = self.pending_loads.remove(pos);
            return;
        };
        task_data.* = ChunkTask{
            .pos = pos,
            .task_type = .generate,
            .chunk = Chunk.init(), // Empty chunk, will be filled by worker
            .neighbors = self.getNeighborChunks(pos),
            .render_chunk = render_chunk_ptr,
        };

        // Submit to thread pool for terrain generation + meshing
        // Priority is now calculated at poll time based on distance to camera
        self.pool.submit(Task{
            .task_type = .generate_and_mesh,
            .data = @ptrCast(task_data),
            .chunk_pos = pos,
            .chunk_task_kind = .generate,
        }) catch {
            // LEAK FIX: Clean up everything if submission fails
            self.allocator.destroy(task_data);
            _ = self.chunk_storage.remove(pos);
            render_chunk_ptr.deinit();
            self.allocator.destroy(render_chunk_ptr);
            _ = self.pending_loads.remove(pos);
            return;
        };
    }

    /// Get neighbor chunk data for face culling
    fn getNeighborChunks(self: *Self, pos: ChunkPos) [6]?*const Chunk {
        const zone = profiler.trace(@src());
        defer zone.end();

        var neighbors: [6]?*const Chunk = .{ null, null, null, null, null, null };

        const offsets = [6]ChunkPos{
            .{ .x = 0, .z = 0, .section_y = -1 }, // down
            .{ .x = 0, .z = 0, .section_y = 1 }, // up
            .{ .x = 0, .z = -1, .section_y = 0 }, // north
            .{ .x = 0, .z = 1, .section_y = 0 }, // south
            .{ .x = -1, .z = 0, .section_y = 0 }, // west
            .{ .x = 1, .z = 0, .section_y = 0 }, // east
        };

        for (0..6) |i| {
            const neighbor_pos = ChunkPos{
                .x = pos.x + offsets[i].x,
                .z = pos.z + offsets[i].z,
                .section_y = pos.section_y + offsets[i].section_y,
            };

            if (self.chunk_storage.get(neighbor_pos)) |neighbor| {
                if (neighbor.getState() == .ready) {
                    neighbors[i] = &neighbor.chunk;
                }
            }
        }

        return neighbors;
    }

    /// Get neighbor chunks for worker thread (called under RCU lock)
    /// Unlike getNeighborChunks, this fetches fresh pointers at processing time
    /// to avoid use-after-free when chunks are unloaded while tasks are queued
    fn getNeighborChunksForWorker(self: *Self, pos: ChunkPos) [6]?*const Chunk {
        var neighbors: [6]?*const Chunk = .{ null, null, null, null, null, null };

        const offsets = [6]ChunkPos{
            .{ .x = 0, .z = 0, .section_y = -1 }, // down
            .{ .x = 0, .z = 0, .section_y = 1 }, // up
            .{ .x = 0, .z = -1, .section_y = 0 }, // north
            .{ .x = 0, .z = 1, .section_y = 0 }, // south
            .{ .x = -1, .z = 0, .section_y = 0 }, // west
            .{ .x = 1, .z = 0, .section_y = 0 }, // east
        };

        for (0..6) |i| {
            const neighbor_pos = ChunkPos{
                .x = pos.x + offsets[i].x,
                .z = pos.z + offsets[i].z,
                .section_y = pos.section_y + offsets[i].section_y,
            };

            if (self.chunk_storage.get(neighbor_pos)) |neighbor| {
                // Only use neighbors that have valid block data (not still loading)
                // .meshing, .ready, and .dirty all have valid chunk data
                if (neighbor.getState() != .loading) {
                    neighbors[i] = &neighbor.chunk;
                }
            }
        }

        return neighbors;
    }

    // ========== Block Access Methods ==========

    /// Get block entry at world position
    /// Returns null if chunk is not loaded or not ready (for rendering)
    pub fn getBlockAt(self: *Self, world_x: i32, world_y: i32, world_z: i32) ?shared.BlockEntry {
        const chunk_pos = ChunkPos.fromBlockPos(world_x, world_y, world_z);

        const rchunk = self.chunk_storage.get(chunk_pos) orelse return null;
        if (rchunk.getState() != .ready) return null;

        // Convert to local coordinates (0-15)
        const local_x: u32 = @intCast(@mod(world_x, CHUNK_SIZE));
        const local_y: u32 = @intCast(@mod(world_y, CHUNK_SIZE));
        const local_z: u32 = @intCast(@mod(world_z, CHUNK_SIZE));

        return rchunk.chunk.getBlockEntry(local_x, local_y, local_z);
    }

    /// Get block entry at world position regardless of chunk state
    /// Used for collision - block data is valid even during remeshing
    /// Returns null if chunk is unloaded or still being generated
    pub fn getBlockAtForCollision(self: *Self, world_x: i32, world_y: i32, world_z: i32) ?shared.BlockEntry {
        const chunk_pos = ChunkPos.fromBlockPos(world_x, world_y, world_z);

        const rchunk = self.chunk_storage.get(chunk_pos) orelse return null;
        // Skip chunks still being generated - their block data isn't ready yet
        // Chunks in meshing/ready/dirty states have valid block data
        if (rchunk.getState() == .loading) return null;

        // Convert to local coordinates (0-15)
        const local_x: u32 = @intCast(@mod(world_x, CHUNK_SIZE));
        const local_y: u32 = @intCast(@mod(world_y, CHUNK_SIZE));
        const local_z: u32 = @intCast(@mod(world_z, CHUNK_SIZE));

        return rchunk.chunk.getBlockEntry(local_x, local_y, local_z);
    }

    /// Set block entry at world position
    /// Returns true if successful, false if chunk is not loaded
    pub fn setBlockAt(self: *Self, world_x: i32, world_y: i32, world_z: i32, entry: shared.BlockEntry) bool {
        const chunk_pos = ChunkPos.fromBlockPos(world_x, world_y, world_z);

        const rchunk = self.chunk_storage.get(chunk_pos) orelse return false;

        // Convert to local coordinates (0-15)
        const local_x: u32 = @intCast(@mod(world_x, CHUNK_SIZE));
        const local_y: u32 = @intCast(@mod(world_y, CHUNK_SIZE));
        const local_z: u32 = @intCast(@mod(world_z, CHUNK_SIZE));

        rchunk.chunk.setBlockEntry(local_x, local_y, local_z, entry);

        // Mark chunk for re-meshing
        self.queueChunkRemesh(chunk_pos, rchunk);

        // Also remesh neighbors if block is on chunk boundary
        if (local_x == 0) self.remeshNeighborIfLoaded(chunk_pos.x - 1, chunk_pos.z, chunk_pos.section_y);
        if (local_x == CHUNK_SIZE - 1) self.remeshNeighborIfLoaded(chunk_pos.x + 1, chunk_pos.z, chunk_pos.section_y);
        if (local_y == 0) self.remeshNeighborIfLoaded(chunk_pos.x, chunk_pos.z, chunk_pos.section_y - 1);
        if (local_y == CHUNK_SIZE - 1) self.remeshNeighborIfLoaded(chunk_pos.x, chunk_pos.z, chunk_pos.section_y + 1);
        if (local_z == 0) self.remeshNeighborIfLoaded(chunk_pos.x, chunk_pos.z - 1, chunk_pos.section_y);
        if (local_z == CHUNK_SIZE - 1) self.remeshNeighborIfLoaded(chunk_pos.x, chunk_pos.z + 1, chunk_pos.section_y);

        return true;
    }

    /// Check if a block at world position is solid (for collision/raycasting)
    /// Uses collision-safe block access that works during chunk remeshing
    pub fn isBlockSolid(self: *Self, world_x: i32, world_y: i32, world_z: i32) bool {
        const entry = self.getBlockAtForCollision(world_x, world_y, world_z) orelse return false;
        return !entry.isAir() and entry.isSolid();
    }

    /// Get the collision shape for a block at world position
    /// Returns VoxelShape.EMPTY for air or out-of-bounds positions
    /// Like Minecraft's BlockState.getCollisionShape()
    pub fn getCollisionShape(self: *Self, world_x: i32, world_y: i32, world_z: i32) shared.VoxelShape {
        const entry = self.getBlockAtForCollision(world_x, world_y, world_z) orelse return shared.voxel_shape.EMPTY;
        if (entry.isAir()) return shared.voxel_shape.EMPTY;
        // Get the shape from the block registry
        return shared.block.getShape(entry.id, entry.state).*;
    }

    /// Helper to remesh a neighbor chunk if loaded
    fn remeshNeighborIfLoaded(self: *Self, chunk_x: i32, chunk_z: i32, section_y: i32) void {
        const neighbor_pos = ChunkPos{ .x = chunk_x, .z = chunk_z, .section_y = section_y };
        if (self.chunk_storage.get(neighbor_pos)) |neighbor_chunk| {
            if (neighbor_chunk.getState() == .ready) {
                self.queueChunkRemesh(neighbor_pos, neighbor_chunk);
            }
        }
    }

    /// Queue a chunk for re-meshing
    fn queueChunkRemesh(self: *Self, pos: ChunkPos, render_chunk_ptr: *RenderChunk) void {
        // Don't clear mesh - keep rendering old mesh until new one arrives
        // Mark as dirty as we know a rebuild is pending (fires on_dirty callback)
        render_chunk_ptr.setState(.dirty);

        // Create task data - remesh uses existing chunk data
        const task_data = self.allocator.create(ChunkTask) catch return;
        task_data.* = ChunkTask{
            .pos = pos,
            .task_type = .remesh,
            .chunk = render_chunk_ptr.chunk,
            .neighbors = self.getNeighborChunks(pos),
            .render_chunk = render_chunk_ptr,
        };

        // Submit to thread pool for meshing only
        // Priority is calculated at poll time - remesh tasks have a quota limit
        self.pool.submit(Task{
            .task_type = .generate_and_mesh,
            .data = @ptrCast(task_data),
            .chunk_pos = pos,
            .chunk_task_kind = .remesh,
        }) catch {
            self.allocator.destroy(task_data);
            return;
        };
    }

    /// Unload chunks beyond unload distance
    fn unloadDistantChunks(self: *Self) void {
        const zone = profiler.trace(@src());
        defer zone.end();

        var to_unload: std.ArrayListUnmanaged(ChunkPos) = .{};
        defer to_unload.deinit(self.allocator);

        {
            const scan_zone = profiler.traceNamed("ScanDistantChunks");
            defer scan_zone.end();

            var iter = self.chunk_storage.iterator();
            while (iter.next()) |entry| {
                const pos = entry.key_ptr.*;
                if (!pos.isWithinDistance(self.player_chunk, self.config.unload_distance)) {
                    to_unload.append(self.allocator, pos) catch continue;
                }
            }
        }

        {
            const unload_zone = profiler.traceNamed("UnloadChunks");
            defer unload_zone.end();
            unload_zone.setValue(to_unload.items.len);

            for (to_unload.items) |pos| {
                self.unloadChunk(pos);
            }
        }
    }

    /// Unload a single chunk
    /// Uses RCU to defer freeing until all workers have exited their critical sections
    fn unloadChunk(self: *Self, pos: ChunkPos) void {
        const zone = profiler.trace(@src());
        defer zone.end();

        if (self.chunk_storage.remove(pos)) |render_chunk_ptr| {

            // Free buffer allocation immediately - workers don't access GPU buffers
            if (self.buffer_manager) |buf_mgr| {
                if (render_chunk_ptr.getBufferAllocation()) |alloc| {
                    buf_mgr.free(alloc);
                }
            }

            // Defer freeing the RenderChunk itself via RCU
            // Workers might still be accessing this chunk's data as a neighbor
            const rcu_instance = self.rcu orelse {
                @panic("RCU must be initialized before unloading chunks - this indicates a bug in initialization order");
            };

            // Create closure data for deferred free
            const DeferredChunkFree = struct {
                chunk: *RenderChunk,
                allocator: std.mem.Allocator,

                fn free(self_ptr: *anyopaque) void {
                    const data: *@This() = @ptrCast(@alignCast(self_ptr));
                    data.chunk.deinit();
                    data.allocator.destroy(data.chunk);
                    data.allocator.destroy(data);
                }
            };

            const deferred = self.allocator.create(DeferredChunkFree) catch {
                @panic("Failed to allocate RCU deferred free - out of memory");
            };
            deferred.* = .{
                .chunk = render_chunk_ptr,
                .allocator = self.allocator,
            };

            rcu_instance.retire(@ptrCast(deferred), DeferredChunkFree.free);
        }
        _ = self.pending_loads.remove(pos);
    }

    /// Worker task processing callback
    fn processTask(ctx: *WorkerContext, task: Task) void {
        const zone = profiler.trace(@src());
        defer zone.end();

        if (task.task_type != .generate_and_mesh) return;

        const task_data_ptr = task.data orelse return;
        const task_data: *ChunkTask = @ptrCast(@alignCast(task_data_ptr));

        // Get per-worker data (contains both manager ref and thread-local mesh context)
        const worker_data: *WorkerData = @ptrCast(@alignCast(ctx.user_data orelse return));
        const self = worker_data.manager;
        const mesh_ctx = worker_data.mesh_context;

        // Defer cleanup of task data
        defer self.allocator.destroy(task_data);

        const shaper = self.shared_model_shaper orelse return;

        // Enter RCU read-side critical section
        // This protects neighbor chunk pointers from being freed while we're using them
        const rcu_instance = self.rcu orelse {
            logger.warn("RCU not initialized, skipping mesh generation", .{});
            return;
        };
        _ = rcu_instance.readLock(@intCast(ctx.id));
        defer rcu_instance.readUnlock(@intCast(ctx.id));

        // RE-FETCH neighbors AFTER acquiring RCU lock!
        // The task_data.neighbors was captured at submission time and may be stale.
        // Chunks could have been unloaded while the task sat in the queue.
        // By re-fetching here (under RCU protection), we get valid pointers.
        const fresh_neighbors = self.getNeighborChunksForWorker(task_data.pos);

        // For generation tasks, generate terrain first (now on worker thread!)
        var chunk_to_mesh: Chunk = undefined;
        var generated_chunk: ?Chunk = null;

        switch (task_data.task_type) {
            .generate => {
                // Generate terrain on worker thread
                if (self.terrain_generator) |terrain_gen| {
                    chunk_to_mesh = terrain_gen.generateChunk(
                        task_data.pos.x,
                        task_data.pos.section_y,
                        task_data.pos.z,
                    );
                } else {
                    // Fallback to test chunk if terrain generator unavailable
                    chunk_to_mesh = Chunk.generateTestChunk();
                }
                generated_chunk = chunk_to_mesh;
            },
            .remesh => {
                // Use existing chunk data
                chunk_to_mesh = task_data.chunk;
            },
        }

        // Generate mesh using thread-local pre-allocated buffers (C2ME-style)
        // This eliminates ~2.4MB of allocations per chunk!
        var mesh = mesh_ctx.generateMesh(
            &chunk_to_mesh,
            task_data.pos,
            fresh_neighbors, // Use freshly fetched neighbors, not stale task_data.neighbors
            shaper,
            self.texture_manager,
        ) catch |err| {
            logger.warn("Failed to generate mesh for chunk: {}", .{err});
            return;
        };

        // Include generated chunk data for main thread to copy
        mesh.generated_chunk = generated_chunk;

        // Push to completed queue
        self.completed_queue.push(mesh) catch |err| {
            logger.warn("Failed to push completed mesh: {}", .{err});
            mesh.deinit();
        };
    }
};
