const std = @import("std");
const volk = @import("volk");
const vk = volk.c;

/// Maximum number of chunks supported in GPU-driven rendering
pub const MAX_CHUNKS: u32 = 65536;

/// Maximum draw commands per render layer (solid, cutout, translucent)
pub const MAX_DRAWS_PER_LAYER: u32 = 100000;

/// Per-layer data for GPU command generation
/// Stored as part of ChunkGPUData, one per render layer
pub const LayerGPUData = extern struct {
    /// Byte offset in vertex buffer
    vertex_offset: u32,
    /// Byte offset in index buffer
    index_offset: u32,
    /// Number of indices to draw
    index_count: u32,
    /// Packed arena indices: vertex_arena << 16 | index_arena
    arena_indices: u32,

    pub const EMPTY = LayerGPUData{
        .vertex_offset = 0,
        .index_offset = 0,
        .index_count = 0,
        .arena_indices = 0,
    };

    pub fn pack(vertex_arena: u16, index_arena: u16) u32 {
        return (@as(u32, vertex_arena) << 16) | @as(u32, index_arena);
    }

    pub fn unpackVertexArena(self: LayerGPUData) u16 {
        return @truncate(self.arena_indices >> 16);
    }

    pub fn unpackIndexArena(self: LayerGPUData) u16 {
        return @truncate(self.arena_indices & 0xFFFF);
    }
};

/// Per-chunk data uploaded to GPU for frustum culling and command generation
/// Layout matches GLSL std430 with explicit padding for alignment
pub const ChunkGPUData = extern struct {
    /// Chunk world position (center point)
    world_pos: [3]f32,
    _pad0: f32 = 0,

    /// AABB minimum corner for frustum culling
    aabb_min: [3]f32,
    _pad1: f32 = 0,

    /// AABB maximum corner for frustum culling
    aabb_max: [3]f32,
    _pad2: f32 = 0,

    /// Per-layer rendering data: [solid, cutout, translucent]
    layers: [3]LayerGPUData,

    _pad3: f32 = 0,

    pub const EMPTY = ChunkGPUData{
        .world_pos = .{ 0, 0, 0 },
        .aabb_min = .{ 0, 0, 0 },
        .aabb_max = .{ 0, 0, 0 },
        .layers = .{ LayerGPUData.EMPTY, LayerGPUData.EMPTY, LayerGPUData.EMPTY },
    };

    comptime {
        // Verify size is what we expect for GPU buffer layout
        // 3 vec4s (world_pos, aabb_min, aabb_max) = 48 bytes
        // 3 LayerGPUData (4 u32 each) = 48 bytes
        // 1 padding float = 4 bytes
        // Total = 100 bytes, but needs 16-byte alignment for vec4s
        std.debug.assert(@sizeOf(ChunkGPUData) == 100);
    }
};

/// Atomic counters for GPU command generation
/// Used by prep.comp and cmdgen.comp shaders
pub const DrawCountData = extern struct {
    /// Compute dispatch dimensions (set by prep.comp for cmdgen.comp)
    dispatch_x: u32 = 0,
    dispatch_y: u32 = 1,
    dispatch_z: u32 = 1,

    /// Draw command counts (atomically incremented by cmdgen.comp)
    solid_count: u32 = 0,
    cutout_count: u32 = 0,
    translucent_count: u32 = 0,

    pub const ZEROED = DrawCountData{};

    comptime {
        std.debug.assert(@sizeOf(DrawCountData) == 24);
    }
};

/// Matches VkDrawIndexedIndirectCommand exactly
/// Generated by cmdgen.comp, consumed by vkCmdDrawIndexedIndirectCount
pub const IndirectDrawCommand = extern struct {
    index_count: u32,
    instance_count: u32,
    first_index: u32,
    vertex_offset: i32,
    first_instance: u32,

    comptime {
        std.debug.assert(@sizeOf(IndirectDrawCommand) == 20);
    }
};

/// Simple slot allocator for tracking chunk GPU metadata indices
/// Uses a free-list for O(1) allocation and deallocation
pub const SlotAllocator = struct {
    const Self = @This();

    /// Free slot indices available for allocation
    free_list: std.ArrayListUnmanaged(u32),
    /// Next slot index to allocate when free list is empty
    next_slot: u32,
    /// Maximum number of slots
    max_slots: u32,
    /// Memory allocator
    allocator: std.mem.Allocator,

    pub const INVALID_SLOT: u32 = 0xFFFFFFFF;

    pub fn init(allocator: std.mem.Allocator, max_slots: u32) Self {
        return Self{
            .free_list = .{},
            .next_slot = 0,
            .max_slots = max_slots,
            .allocator = allocator,
        };
    }

    pub fn deinit(self: *Self) void {
        self.free_list.deinit(self.allocator);
    }

    /// Allocate a slot, returns INVALID_SLOT if none available
    pub fn alloc(self: *Self) u32 {
        // First try to reuse a freed slot
        if (self.free_list.pop()) |slot| {
            return slot;
        }

        // Otherwise allocate a new slot
        if (self.next_slot < self.max_slots) {
            const slot = self.next_slot;
            self.next_slot += 1;
            return slot;
        }

        return INVALID_SLOT;
    }

    /// Free a slot for reuse
    pub fn free(self: *Self, slot: u32) void {
        if (slot == INVALID_SLOT or slot >= self.next_slot) return;
        self.free_list.append(self.allocator, slot) catch {
            // If we can't track the free slot, it's leaked but not critical
        };
    }

    /// Get the number of allocated slots
    pub fn getAllocatedCount(self: *const Self) u32 {
        return self.next_slot - @as(u32, @intCast(self.free_list.items.len));
    }

    /// Get the high-water mark (maximum slot index ever allocated)
    pub fn getHighWaterMark(self: *const Self) u32 {
        return self.next_slot;
    }
};

// Buffer size calculations
pub fn getChunkMetadataBufferSize() u64 {
    return MAX_CHUNKS * @sizeOf(ChunkGPUData);
}

pub fn getVisibilityBufferSize() u64 {
    return MAX_CHUNKS * @sizeOf(u32);
}

pub fn getDrawCountBufferSize() u64 {
    return @sizeOf(DrawCountData);
}

pub fn getGPUDrawBufferSize() u64 {
    return 3 * MAX_DRAWS_PER_LAYER * @sizeOf(IndirectDrawCommand);
}

test "LayerGPUData arena packing" {
    const layer = LayerGPUData{
        .vertex_offset = 0,
        .index_offset = 0,
        .index_count = 0,
        .arena_indices = LayerGPUData.pack(5, 3),
    };
    try std.testing.expectEqual(@as(u16, 5), layer.unpackVertexArena());
    try std.testing.expectEqual(@as(u16, 3), layer.unpackIndexArena());
}

test "SlotAllocator basic operations" {
    var allocator = SlotAllocator.init(std.testing.allocator, 100);
    defer allocator.deinit();

    const slot0 = allocator.alloc();
    const slot1 = allocator.alloc();
    const slot2 = allocator.alloc();

    try std.testing.expectEqual(@as(u32, 0), slot0);
    try std.testing.expectEqual(@as(u32, 1), slot1);
    try std.testing.expectEqual(@as(u32, 2), slot2);
    try std.testing.expectEqual(@as(u32, 3), allocator.getAllocatedCount());

    allocator.free(slot1);
    try std.testing.expectEqual(@as(u32, 2), allocator.getAllocatedCount());

    // Next alloc should reuse slot1
    const slot3 = allocator.alloc();
    try std.testing.expectEqual(@as(u32, 1), slot3);
}
